package hw5;

import hw5.dialog.DialogForm;
import hw5.dialog.DialogTree;
import hw5.game.Agent;
import hw5.game.CharacterCreationForm;
import hw5.game.CombatForm;
import hw5.game.Enemy;
import hw5.game.Game;
import hw5.game.MapForm;
import hw5.game.Player;
import hw5.pathfinding.GraphLoader;
import hw5.pathfinding.PositionedGraph;
import hw5.pathfinding.PathFindingForm;

/**
 *
 * @author baylor
 */
public class MainMenuForm extends javax.swing.JFrame
{
	public MainMenuForm()
	{
		initComponents();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dialogButton = new javax.swing.JButton();
        pathingButton = new javax.swing.JButton();
        combatButton = new javax.swing.JButton();
        characterDesignButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        dialogButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dialogButton.setText("Talk to Someone");
        dialogButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                dialogButtonActionPerformed(evt);
            }
        });

        pathingButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pathingButton.setText("Find a Path");
        pathingButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pathingButtonActionPerformed(evt);
            }
        });

        combatButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combatButton.setText("Get in a Fight");
        combatButton.setToolTipText("");
        combatButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                combatButtonActionPerformed(evt);
            }
        });

        characterDesignButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        characterDesignButton.setText("Make a Character");
        characterDesignButton.setToolTipText("");
        characterDesignButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                characterDesignButtonActionPerformed(evt);
            }
        });

        playButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playButton.setText("Play a Game");
        playButton.setToolTipText("");
        playButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                playButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(characterDesignButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dialogButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(pathingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(combatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pathingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(characterDesignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dialogButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dialogButtonActionPerformed
    {//GEN-HEADEREND:event_dialogButtonActionPerformed
		DialogForm form = new DialogForm();
		form.setVisible(true);
    }//GEN-LAST:event_dialogButtonActionPerformed

    private void pathingButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pathingButtonActionPerformed
    {//GEN-HEADEREND:event_pathingButtonActionPerformed
//		String mapName = "maps/simplestMap.txt";
//		String mapName = "maps/mapA.txt";
		String mapName = "maps/mapB.txt";
		PositionedGraph graph = GraphLoader.loadGraph(mapName);
		PathFindingForm form = new PathFindingForm(graph);
		form.setVisible(true);
    }//GEN-LAST:event_pathingButtonActionPerformed

    private void characterDesignButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_characterDesignButtonActionPerformed
    {//GEN-HEADEREND:event_characterDesignButtonActionPerformed
		CharacterCreationForm form = new CharacterCreationForm();
		form.setVisible(true);
		Agent agent = form.getAgent();

    }//GEN-LAST:event_characterDesignButtonActionPerformed

    private void combatButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_combatButtonActionPerformed
    {//GEN-HEADEREND:event_combatButtonActionPerformed
  		Agent player  = new Player("player");
		player.health = 100;
		Agent enemy   = new Enemy("pirate");
		enemy.health  = 10000;

		CombatForm form = new CombatForm(player, enemy);
		form.setVisible(true);
    }//GEN-LAST:event_combatButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_playButtonActionPerformed
    {//GEN-HEADEREND:event_playButtonActionPerformed
		Game game    = Game.getInstance();
		MapForm form = new MapForm(game);
		form.setVisible(true);
    }//GEN-LAST:event_playButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton characterDesignButton;
    private javax.swing.JButton combatButton;
    private javax.swing.JButton dialogButton;
    private javax.swing.JButton pathingButton;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
